In [56]:
import pandas as pd

In [57]:
dt = pd.read_excel("接入deepseek的医院-医院版.xlsx")

In [65]:
dt["医院等级三分类"]=dt["医院评级"]
dt["医院等级三分类"].loc[dt["医院等级三分类"]=="三甲"]= '三级'
dt["医院等级三分类"].loc[dt["医院等级三分类"]=="三乙"]= '三级'
dt["医院等级三分类"].loc[dt["医院等级三分类"]=="二甲"]= '二级'
dt2 =dt[dt["医院等级三分类"].isin(['三级','二级','一级','未定级'])]

/var/folders/20/qpfbj54535n89h28ft3x9zhr0000gn/T/ipykernel_72268/2770511856.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt["医院等级三分类"].loc[dt["医院等级三分类"]=="三甲"]= '三级'
/var/folders/20/qpfbj54535n89h28ft3x9zhr0000gn/T/ipykernel_72268/2770511856.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt["医院等级三分类"].loc[dt["医院等级三分类"]=="三乙"]= '三级'
/var/folders/20/qpfbj54535n89h28ft3x9zhr0000gn/T/ipykernel_72268/2770511856.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt["医院等级三分类"].loc[dt["医院等级三分类"]=="二甲"]= '二级'

In [67]:
dt2["医院等级三分类"].value_counts().to_frame()

    医院等级三分类
三级      218
二级       41
一级        2

In [68]:
dt2.to_csv("接入deepseek的医院-医院版.csv",index=False)

In [72]:
dt2[["医院等级三分类",'医院地区']].value_counts(sort=True).to_frame()

                   0
医院等级三分类 医院地区
三级      广西壮族自治区   20
        四川省       16
        广东省       16
        江苏省       15
        山东省       15
        浙江省       11
        安徽省       11
        陕西省       11
        北京市       11
        湖北省       10
        福建省       10
        湖南省        8
        河北省        7
二级      广西壮族自治区    6
三级      内蒙古自治区     6
        河南省        6
二级      安徽省        5
        河北省        5
三级      重庆市        5
        辽宁省        5
        山西省        4
二级      广东省        4
三级      上海市        4
        贵州省        4
        江西省        4
        云南省        3
        黑龙江省       3
二级      四川省        3
三级      吉林省        3
二级      山东省        3
三级      天津市        3
        宁夏回族自治区    3
        甘肃省        2
二级      湖北省        2
        陕西省        2
        宁夏回族自治区    2
        重庆市        1
        江苏省        1
        福建省        1
        浙江省        1
一级      上海市        1
二级      新疆维吾尔自治区   1
        吉林省        1
        内蒙古自治区     1
        上海市        1
三级      青海省        1
一级      江苏省        1
三级      新疆维吾尔自治区   1
二级      黑龙江省       1

In [73]:
dt2['医院地区'].value_counts(sort=True).to_frame()

          医院地区
广西壮族自治区     26
广东省         20
四川省         19
山东省         18
江苏省         17
安徽省         16
陕西省         13
浙江省         12
河北省         12
湖北省         12
福建省         11
北京市         11
湖南省          8
内蒙古自治区       7
上海市          6
重庆市          6
河南省          6
辽宁省          5
宁夏回族自治区      5
吉林省          4
山西省          4
黑龙江省         4
贵州省          4
江西省          4
天津市          3
云南省          3
新疆维吾尔自治区     2
甘肃省          2
青海省          1

In [74]:
dt2['部署版本'].value_counts().to_frame()

                                                   部署版本
DeepSeek-R1                                         220
DeepSeek-R1:671B（满血版）                                10
DeepSeek-R1:70B                                       6
DeepSeek-R1:32B                                       3
DeepSeek-R1:32B + Qwen2.5-VL-7B-Instruct              1
DeepSeek、阿里千问                                         1
DeepSeek-V3 满血版                                       1
多模型协同                                                 1
结合天河・天元、WiNGPT 模型                                     1
DeepSeek-R1:32b                                       1
DeepSeek-R1:671B（满血版）本地化部署\nDeepSeek-R1:70B云端部署       1
DeepSeek-R1-70B/32B/Janus-Pro-7B                      1
DeepSeek 与自研素问医疗大模型融合                                 1
DeepSeek-R1:14B\nDeepSeek-R1:32B                      1
Deepseek-R1:32B                                       1
DeepSeek + 豆包                                         1
DeepSeek-R1 + 数坤坤模型                                   1
DeepSeek + 腾讯混元                                       1
DeepSeek-R1:671B（满血版） + 腾讯混元大模型                       1
DeepSeek-R1:671B（满血版）\nDeepSeek-R1:70B                1
DeepSeek-R1:32B \n医疗云DeepSeek-R1:671B（满血版）            1
DeepSeek-R1:671B（满血版）+量子安全                            1
deepseek、qwen                                         1
DeepSeek-R1:14B\nDeepSeek-R1:32B\nDeepSeek-R1:70B     1
DeepSeek + 灵医大模型                                      1
DeepSeek-R1:32B\nDeepSeek-R1:70B                      1

In [83]:
dt3 = pd.read_excel("接入deepseek的医院-医院版-N261版本.xlsx",sheet_name=3)

In [92]:
dt3[['最高R1版本及参数','医院等级三分类']].value_counts(sort=True).to_frame()

                    0
最高R1版本及参数 医院等级三分类
671B（满血版） 三级       14
70B       三级        9
32B       三级        8

In [93]:
dt3[['最高R1版本及参数','医院地区']].value_counts(sort=True).to_frame()

                   0
最高R1版本及参数 医院地区
671B（满血版） 广东省      5
32B       广西壮族自治区  3
          四川省      2
70B       广西壮族自治区  2
          重庆市      2
32B       河北省      2
671B（满血版） 山东省      1
          北京市      1
          江苏省      1
          河北省      1
          河南省      1
32B       福建省      1
671B（满血版） 湖北省      1
          甘肃省      1
          青海省      1
70B       北京市      1
          安徽省      1
          山东省      1
          湖南省      1
          福建省      1
671B（满血版） 浙江省      1

In [91]:
dt3[['最高R1版本及参数','医院等级三分类','医院地区']].value_counts(sort=True).to_frame()

                           0
最高R1版本及参数 医院等级三分类 医院地区
671B（满血版） 三级      广东省      5
32B       三级      广西壮族自治区  3
                  四川省      2
70B       三级      广西壮族自治区  2
                  重庆市      2
32B       三级      河北省      2
671B（满血版） 三级      山东省      1
                  北京市      1
                  江苏省      1
                  河北省      1
                  河南省      1
32B       三级      福建省      1
671B（满血版） 三级      湖北省      1
                  甘肃省      1
                  青海省      1
70B       三级      北京市      1
                  安徽省      1
                  山东省      1
                  湖南省      1
                  福建省      1
671B（满血版） 三级      浙江省      1